version: '3'
services:
  channels:
    build: .
    ports:
      - "80:8000"
      - "8001:8001"
    volumes:
      - .:/app
    links:
      - redis
  redis:
    image: "redis:latest"
    restart: on-failure
